language: python

sudo: false

python:
  - "3.7"

os:
  - linux

services:
  - xvfb

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
    sudo apt-get update && sudo apt-get install -y libsecret-1-0;
    fi

install:
  - nvm install 10.16.2;
  - npm install
  - npm run compile
  - pip install cfn-lint pydot

script:
  - npm run lint
  - npm run test
