language: python

sudo: false

os:
  - linux

before_install:
  - if [ $TRAVIS_OS_NAME == "linux" ]; then
      export DISPLAY=:99.0;
      sh -e /etc/init.d/xvfb start;
      sudo apt-get update && sudo apt-get install -y libsecret-1-0;
    fi

install:
  - TRAVIS_NODE_VERSION="6";
      # Clear out whatever version of NVM Travis has as it is old.
  - rm -rf ~/.nvm;
      # Grab NVM.
  - git clone https://github.com/creationix/nvm.git ~/.nvm;
      # Checkout the latest stable tag.
      # Note that you can just hardcode a preferred version here.
  - (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`);
      # Install the desired version of Node
  - source ~/.nvm/nvm.sh;
  - nvm install $TRAVIS_NODE_VERSION;
  - npm install
  - npm run vscode:prepublish
  - pip install cfn-lint

script:
  - npm run lint
  - npm run test
