on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  release:
    types:
    - created
jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - run: npm install
    - run: npm run compile
    - run: npm run lint
      if: runner.os != 'Linux'
    - run: xvfb-run -a npm run test
      if: runner.os == 'Linux'
    - name: Publish
      if: success() && startsWith( github.ref, 'refs/tags/releases/') && matrix.os == 'ubuntu-latest'
      run: vsce publish -p ${{ secrets.VSCE_PAT }}

