on:
 schedule: 
  - cron: '* * * * *'
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: touch hello-world.txt
      - uses: peter-evans/create-pull-request@v3
